name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.9"

    - name: Install dependencies
      run: |
        cd project
        pip install -r requirements.txt

    - name: Install Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox

    - name: Install geckodriver
      run: |
        GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.tag_name')
        wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        tar -xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        rm geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz

    - name: Run tests
      run: |
        cd project
        chmod +x tests.sh
        ./tests.sh

    - name: Upload database artifact
      uses: actions/upload-artifact@v4
      with:
        name: database
        path: project/data/educationAndEconomy_BrazilColombiaPeru.db